bcgov/bcparks-ar-admin

src/app/forms/backcountry-camping/sections/backcountry-camping-section/backcountry-camping-section.component.html
src/app/forms/day-use/sections/people-and-vehicles/people-and-vehicles.component.html
src/app/forms/day-use/sections/picnic-shelters/picnic-shelters.component.html
src/app/forms/frontcountry-cabins/sections/frontcountry-cabins-section/frontcountry-cabins-section.component.html
src/app/forms/frontcountry-camping/sections/additional-vehicles/additional-vehicles.component.html
src/app/forms/frontcountry-camping/sections/camping-party-nights/camping-party-nights.component.html
src/app/forms/group-camping/sections/standard-rate-groups/standard-rate-groups.component.html
src/app/forms/group-camping/sections/youth-rate-groups/youth-rate-groups.component.html
src/app/shared/components/forms/text-input/text-input.component.html
src/app/shared/components/forms/text-input/text-input.component.ts

NOBUG
GH Issue #68  
This change removes `0` from all form placeholders to mitigate confusion over what is `null` and what is actually `0`.  The default empty field placeholder is currently set to read `No data` as a clear indicator the field is empty, but this can easily be changed to something more appropriate in the future. Hyphens `-` are used elsewhere in the code to denote empty fields but still feel unclear when used as placeholders in editable fields. Leaving empty fields 'blank' also makes it difficult to understand the field is editable at a quick glance.

NOBUG: changing placeholder text

---

src/app/enter-data/accordion-manager/accordion-manager.component.ts
src/app/enter-data/accordion-manager/backcountry-cabins-accordion/backcountry-cabins-accordion.component.ts
src/app/enter-data/accordion-manager/backcountry-camping-accordion/backcountry-camping-accordion.component.ts
src/app/enter-data/accordion-manager/boating-accordion/boating-accordion.component.ts
src/app/enter-data/accordion-manager/day-use-accordion/day-use-accordion.component.ts
src/app/enter-data/accordion-manager/frontcountry-cabins-accordion/frontcountry-cabins-accordion.component.ts
src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.ts
src/app/enter-data/accordion-manager/group-camping-accordion/group-camping-accordion.component.ts
src/app/enter-data/enter-data.component.ts
src/app/enter-data/sub-area-search/sub-area-search.component.ts
src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
src/app/forms/backcountry-camping/backcountry-camping.component.ts
src/app/forms/boating/boating.component.ts
src/app/forms/day-use/day-use.component.ts
src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
src/app/forms/group-camping/group-camping.component.ts
src/app/header/header.component.ts
src/app/shared/components/accordion/accordion.component.ts
src/app/shared/components/breadcrumb/breadcrumb.component.ts
src/app/shared/components/date-picker/date-picker.component.ts
src/app/shared/components/forms/base-form/base-form.component.ts
src/app/shared/components/infinite-loading-bar/infinite-loading-bar.component.ts
src/app/shared/components/sidebar/sidebar.component.ts
src/app/shared/components/text-to-loading-spinner/text-to-loading-spinner.component.ts

#112 
Changing subscriptions from an array-based model to a single `Subscription` object per component. Instead of iterating through an array of subscriptions and unsubscribing to each one, new subscriptions are added to the `Subscription` object using `Subscription.add()`. When the component is destroyed, calling `Subscription.unsubscribe()` terminates all subs simultaneously without iteration.

112: consolidating subscriptions to mitigate memory leaks

---

src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/guards/auth.guard.spec.ts
src/app/guards/auth.guard.ts
src/app/header/header.component.html
src/app/header/header.component.ts
src/app/login/login.component.html
src/app/login/login.component.scss
src/app/login/login.component.ts
src/app/not-authorized/not-authorized.component.html
src/app/not-authorized/not-authorized.component.spec.ts
src/app/not-authorized/not-authorized.component.ts
src/app/services/keycloak.service.spec.ts
src/app/services/keycloak.service.ts

BRS-653
https://bcparksdigital.atlassian.net/browse/BRS-653
- Added a custom login page for Attendance and Revenue
- Changed the existing Not Authorized page to use a single column layout (similar to the new login page)
- Infers the selected Identity Provider from the JWT token after successful log in and stores it in sessionStorage so future login requests to Keycloak will use the same IDP, even if the application is reloaded and its state is lost.

BRS-653: A&R Login Page

---

src/app/login/login.component.html

BRS-653
https://bcparksdigital.atlassian.net/browse/BRS-653
Updated the URL for A&R BCeID registration based on bug found by QA.  
The wrong URL was copied/pasted from Day Use Pass.

BRS-653: Update the BCeID registration url (was set to the DUP url)

---

.github/workflows/deploy_dev.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_test.yml
.github/workflows/pr-linting.yaml
.github/workflows/pr-tests.yaml

NOBUG
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

NOBUG updating Actions to use Node16

---

src/app/export-reports/export-reports.component.ts
src/app/resolvers/export.resolver.ts
src/app/services/export.service.ts

BRS-849
https://bcparksdigital.atlassian.net/browse/BRS-849
Exporter would continually poll for results even if report generation had failed. It would poll until the jwt expired at around 15 minutes. This change implements some smarter error checking.
With the associated API changes in https://github.com/bcgov/bcparks-ar-api/pull/88, we can now more easily check the status of a currently running job (`jobObj.progressState`). The error state has been added to jobs so that the front end knows when to stop polling the back end for a result.
If the exporter runs into an error, it will reattempt report generation a fixed number of times before giving up. If no errors are encountered, it will poll the API for a fixed time until giving up. Values for error retry limits, timeouts, and polling …

BRS-849 exporter error handling and retry limiting

---

.github/workflows/deploy_dev.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_test.yml
.github/workflows/pr-linting.yaml
.github/workflows/pr-tests.yaml
.github/workflows/zap-scan.yaml
package.json
yarn.lock

NOBUG
Updating workflow version due to save-state deprecation.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

NOBUG: Updating workflow version due to save-state deprecation

---

src/app/enter-data/sub-area-search/sub-area-search.component.spec.ts
src/app/enter-data/sub-area-search/sub-area-search.component.ts
src/app/shared/utils/utils.spec.ts

failures due to order of operations of `setMonth` and `setDate`.
BRS-1041
https://bcparksdigital.atlassian.net/browse/BRS-1041
This fixes a bug in bounds checking for the date picker.  It was inaccurately resolving the router to a future date, instead of resetting the controls' value to the previously selected date.

BRS-1041: Fixing date handling in date picker. Fixed unit testing

---

karma.conf.js
src/app/enter-data/enter-data.component.ts
src/app/enter-data/enter-data.module.ts
src/app/enter-data/sub-area-search/sub-area-search.component.html
src/app/enter-data/sub-area-search/sub-area-search.component.scss
src/app/enter-data/sub-area-search/sub-area-search.component.spec.ts
src/app/enter-data/sub-area-search/sub-area-search.component.ts
src/app/services/park.service.spec.ts
src/app/services/park.service.ts
src/app/shared/components/typeahead/typeahead.component.html
src/app/shared/components/typeahead/typeahead.component.scss
src/app/shared/components/typeahead/typeahead.component.ts
src/app/shared/utils/utils.spec.ts
src/app/shared/utils/utils.ts

BRS-972
https://bcparksdigital.atlassian.net/browse/BRS-972
This ticket is part I of updating the A&R UI to handle historical reports - the `enter-data` search has been modified to display `historical` pills next to legacy parks/subareas.
Some QOL (NOBUG) improvements made while in this area of code: now both the park and subarea fields support typeahead predictions. Also, these field changes come with an ability to clear the field on a button press rather than focusing on the field, selecting and then deleting the text.
The `ngbTypeahead` package has a few limitations: for example, the `historical` pill can only be shown in the dropdown, and not in the field when an item is selected.

BRS-972: Part I - revamping enter-data search

---

package.json
yarn.lock

This updates keycloak-js to latests 'working' version.  The very latest is a broken package on npm.

NOBUG: Security updates.

---

src/app/services/api.service.ts
src/app/services/data.service.ts
src/app/services/keycloak.service.ts
src/app/services/sub-area.service.ts
src/app/services/variance.service.spec.ts
src/app/services/variance.service.ts
src/app/shared/components/date-picker/date-picker.component.ts
src/app/shared/utils/constants.ts
src/app/variance-search/variance-filters/variance-filters.component.html
src/app/variance-search/variance-filters/variance-filters.component.spec.ts
src/app/variance-search/variance-filters/variance-filters.component.ts
src/app/variance-search/variance-list/variance-accordion/variance-accordion.component.html
src/app/variance-search/variance-list/variance-accordion/variance-accordion.component.spec.ts
src/app/variance-search/variance-list/variance-accordion/variance-accordion.component.ts
src/app/variance-search/variance-list/variance-list.component.html
src/app/variance-search/variance-list/variance-list.component.spec.ts
src/app/variance-search/variance-list/variance-list.component.ts

BRS-1214
https://bcparksdigital.atlassian.net/browse/BRS-1214
Front end changes for BRS-1214. Thanks ChatGPT:
- Added a new method `put(pk, obj, queryParamsObject = null as any)` to the `ApiService` class.
- The `put` method sends a PUT request to the API with the provided `pk` (primary key) and `obj` (data object) along with optional query parameters (`queryParamsObject`).
- The method returns an observable that will emit the response from the API.
- Added a new method `appendItemValue(id, value)` to the `DataService` class.
- The `appendItemValue` method is used to concatenate a new value to the existing array value associated with the provided `id` in the data service.
- If the `id` does not exist in the data service, a new item with the provided `id` and `value` is initialized.
- If …

BRS-1214 Review data filter updates

---

src/app/export-reports/export-reports.component.spec.ts
src/app/export-reports/export-reports.component.ts

BRS-1263
https://bcparksdigital.atlassian.net/browse/BRS-1263
Old code was setting `2023` as the maxDate for the fiscal year range picker in the variance export page. Technically the fiscal year ends in March of the following year. New max date set to the next instance of 00:00 Apr. 1st (UTC).
Deploy with [API 217](https://github.com/bcgov/bcparks-ar-api/pull/217) for changes to take effect.

BRS-1263 fiscal year end change

---

src/app/enter-data/sub-area-search/sub-area-search.component.ts

[BRS-250](https://github.com/orgs/bcgov/projects/49/views/2?pane=issue&itemId=36685732)
[https://github.com/orgs/bcgov/projects/49/views/2?pane=issue&itemId=36685732](https://bcparksdigital.atlassian.net/browse/BRS-123)
Removed the historical "Bubble" from isLegacy parks on the front end. 
The other part of this ticket was about adding new subareas to parks with the isLegacy parameter. I was able to do this in the DEV environment with no changes to the api.

BRS-250: Remove historical badge from legacy parks

---

src/app/forms/root-form/root-form.component.ts

Patch for https://github.com/bcgov/bcparks-ar-admin/issues/255.
Discarding a form after triggering a variance persists the variance tooltips between other records of the same activity type. With this fix, the triggered variance fields are cleared on navigation to the page so the call starts fresh.

PDR-255-5 reset variance tooltip on form discard

---

package.json
yarn.lock

Fixes #325 
The typeahead in the ngds-forms package uses string matching when selecting typeahead options. It picks the first option with a string match with what you selected, but it used to work on a word by word basis. If you selected `Goldstream Corridor`, the string matcher would look for `Goldstream` and `Corridor` individually, which lead to the incorrect subarea `Goldstream` getting selected first. 
The typeahead in the form engine has been updated to require a 100% string match now, so `Goldstream Corridor` must match 'Goldstream Corridor' in its entirety. 
It would be bad practice for a typeahead to have two options that share the exact same display string (eg two options that both say `Goldstream Corridor` but refer to different subareas). A console warning has been added to …

BRS-325 updating form engine package to fix typeahead issue

---

.github/workflows/deploy_dev.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_test.yml
template.yaml

BRS-359
#359 
- The real fix to the double forward slash in Cloudfront, etc.

BRS-359-4: Revert BaseHref Change

---

.github/workflows/deploy_prod.yml
.github/workflows/deploy_test.yml

BRS-359
#359 
- The REAL Fix for GitHub Actions for test/prod deploy, should properly create version directories in the S3 bucket on upload

BRS-359-6: Fix S3 $DIR_NAME Variable in Test/Prod Deploy Actions 

---

src/app/enter-data/accordion-manager/backcountry-camping-accordion/backcountry-camping-accordion.component.ts

BRS-368
[BRS-368](https://github.com/bcgov/bcparks-ar-admin/issues/368)
- Backcountry Camping records will now show `grossCampingRevenue` data on frontend for isLegacy records
- Corresponds to the migration to move several subareas into one subarea (Marine Sites) and make the old subareas "historic" in the admin.

BRS-368: Show Gross Camping Revenue on Historic Records after Migration

---

src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.spec.ts
src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.ts
src/app/forms/frontcountry-camping/frontcountry-camping.component.html
src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
src/app/services/formula.service.ts
src/app/services/winter-toggle.service.spec.ts
src/app/services/winter-toggle.service.ts
src/app/shared/components/accordion/summary-section/summary-section.component.html
src/app/shared/components/accordion/summary-section/summary-section.component.ts
src/app/shared/utils/constants.ts
src/app/shared/utils/mock.data.ts

BRS-389
#389 
- A toggle-able`Winter` button will show `Winter standard` and `Winter SSCFE` in the Frontcountry Camping fields
- Winter toggle button persists through user session as a service
- Winter camping fields included in attendance calculation and export fields
- Tweak to the summary section on Enter Data to show winter camping fields with appropriate headings

BRS-389 - Implement Winter Camping Data Fields

---

package.json
yarn.lock

Relates to https://github.com/bcgov/parks-data-register/issues/564. 
Upgrades to `keycloak-js@25.0.6` instead of the recommended `keycloak-js@26.2.0`. Will need to bump the angular version before upgrading to the recommended version.

AR-564: upgrading keycloak-js as temporary fix

---

src/app/manage-subareas/subarea-form/subarea-form.component.html
src/app/manage-subareas/subarea-form/subarea-form.component.ts

As described in #427 comments, there is a graphical bug that occurs in the dropdown menus when the invalid state is triggered. The dropdown menu appears behind other menu entry fields (particularly text entry boxes). 
This is a bug with the NGDS-Toolkit form engine and has been captured here: https://github.com/digitalspace/ngds-toolkit/issues/24.
A temporary workaround is simply not displaying the invalid state of the fields. The validity is still enforced (you cannot proceed until the whole form is valid), however, the red invalid state with invalid reason will no longer be displayed (was not in the designs anyways).

AR-427-5 removing invalid field display to prevent dropdown graphics bug

---

src/app/footer/footer.component.html
src/app/footer/footer.component.scss

Ticket: [492](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=91284780&issue=bcgov%7Cparks-reso-public%7C492)
Notes: Added land acknowledgment to foot. Adjusted size of existing footer. Moved BC Gold border to above land acknowledgement. There were no designs originally included for AR but this was a close mix of examples and pre-existing footer.

BRS-492: Add land acknowledgment to footer

---

src/app/forms/backcountry-cabins/backcountry-cabins.component.html
src/app/forms/backcountry-camping/backcountry-camping.component.html
src/app/forms/boating/boating.component.html
src/app/forms/frontcountry-cabins/frontcountry-cabins.component.html
src/app/forms/frontcountry-camping/frontcountry-camping.component.html
src/app/forms/group-camping/group-camping.component.html
src/app/forms/root-form/root-form.component.ts
src/app/shared/utils/constants.ts

Relates to #393.
Variance reasons were added as an array of objects to the `constants.ts` file under `varianceReasons`. They all have a `value`, and if there are subreasons, they are listed under `subReasons`. 
Each form pulls in `Constants.varianceReasons` and is initialized with 'Other'. A picklist shows the available variance reasons. If one is selected, the `notes` field is populated with the reason. If the reason has subreasons, another picklist appears with the subreasons and the same behaviour: `notes` field adopts the subreason value if selected. The field is saved the same way as usual.
The form doesn't force the user to pick anything. 
Upon loading a previously saved activity, the notes field will have the correct value, but the variance and subvariance selections will return to …

AR-393 adding standardized variance reasons
