bcgov/bcparks-ar-admin

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- terraform/dev/terragrunt.hcl
- terraform/prod/terragrunt.hcl
- terraform/src/budget.tf
- terraform/src/cloudfront.tf
- terraform/src/main.tf
- terraform/src/outputs.tf
- terraform/src/roles.tf
- terraform/src/route.tf
- terraform/src/variables.tf
- terraform/terragrunt.hcl
- terraform/test/terragrunt.hcl
BRS-507
https://bcparksdigital.atlassian.net/browse/BRS-507
GH-actions workflow for bcparks-ar-admin
> BRS-507 admin gh-actions

- angular.json
BRS-507
https://bcparksdigital.atlassian.net/browse/BRS-507
Increasing initialization budgets
> Increase budgets

- src/env.js.template
NOBUG
Fixing config. Adding window.__env.configEndpoint = localConfigEndpoint;.
> NOBUG: Fixing config

- src/app/shared/components/forms/calculation-display/calculation-display.component.html
- src/app/shared/components/forms/calculation-display/calculation-display.component.spec.ts
- src/app/shared/components/forms/calculation-display/calculation-display.component.ts
- src/app/shared/components/forms/calculation-display/calculation-display.module.ts
- src/env.js
NOBUG
Creating module for calculation display for forms.
> NOBUG: Creating module for calculation display for forms

- src/env.js
> NOBUG: Updating api url

- src/app/shared/components/forms/calculation-display/calculation-display.component.html
- src/app/shared/components/forms/text-input/text-input.component.html
- src/app/shared/components/forms/text-input/text-input.component.spec.ts
- src/app/shared/components/forms/text-input/text-input.component.ts
- src/app/shared/components/forms/text-input/text-input.module.ts
NOBUG
Initializing text input module
> NOBUG: Initializing text input module

- src/app/app.component.html
- src/app/enter-data/enter-data.component.html
- src/app/enter-data/enter-data.component.ts
- src/app/enter-data/enter-data.module.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.html
- src/app/enter-data/sub-area-search/sub-area-search.component.spec.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/shared/components/centered-text-block/centered-text-block.component.html
- src/app/shared/components/centered-text-block/centered-text-block.component.scss
- src/app/shared/components/centered-text-block/centered-text-block.component.spec.ts
- src/app/shared/components/centered-text-block/centered-text-block.component.ts
- src/app/shared/components/centered-text-block/centered-text-block.module.ts
NOBUG
Updating enter data page.
> NOBUG: Updating enter data page

- src/app/services/config.service.ts
NOBUG
Fixing issue with config service.
> NOBUG: Fixing issue with config service

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.html
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/services/api.service.ts
- src/app/services/auto-fetch.service.ts
- src/app/services/park.service.ts
- src/app/shared/components/typeahead/typeahead.component.html
- src/app/shared/components/typeahead/typeahead.component.ts
BRS-554
https://bcparksdigital.atlassian.net/browse/BRS-554
Adding autofetch for parks list.
> BRS-554: Adding autofetch for parks list

- src/app/enter-data/enter-data.component.html
- src/app/enter-data/enter-data.component.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.html
- src/app/enter-data/sub-area-search/sub-area-search.component.spec.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/resolvers/sub-area.resolver.ts
- src/app/services/sub-area.service.spec.ts
- src/app/services/sub-area.service.ts
BRS-513
https://bcparksdigital.atlassian.net/browse/BRS-513
Editing sub area list service for populating activities.
> BRS-513: Populating activities.

- src/app/enter-data/accordion-manager/accordion-manager.component.html
- src/app/enter-data/accordion-manager/accordion-manager.component.spec.ts
- src/app/enter-data/accordion-manager/accordion-manager.component.ts
- src/app/enter-data/enter-data.component.html
- src/app/enter-data/enter-data.module.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/shared/components/accordion/accordion.component.html
- src/app/shared/components/accordion/accordion.component.spec.ts
- src/app/shared/components/accordion/accordion.component.ts
- src/app/shared/components/accordion/accordion.module.ts
- src/app/shared/components/accordion/summary-section/summary-section.component.html
- src/app/shared/components/accordion/summary-section/summary-section.component.spec.ts
- src/app/shared/components/accordion/summary-section/summary-section.component.ts
- src/app/shared/components/forms/calculation-display/calculation-display.component.html
- src/app/shared/components/forms/calculation-display/calculation-display.component.scss
- src/app/shared/components/forms/calculation-display/calculation-display.component.ts
- src/app/shared/utils/constants.ts
- src/assets/styles/base/base.scss
- src/assets/themes/_variables.scss
BRS-555 pt 1 - adding Accordion UI components
BRS-555
https://bcparksdigital.atlassian.net/browse/BRS-555
First pass of an accordion UI component to display the readonly form data of a subarea. This implementation is getting complex so I am committing an intermediate step. Some mock data has been included to show what a full accordion might look like.  Addition of Add/Edit form buttons, wiring up to API, and general refinement of components to follow.
> BRS-555 pt 1 - adding Accordion UI components

- src/app/services/sub-area.service.ts
- src/app/shared/utils/constants.ts
NOBUG
Fetch activity details service.
> NOBUG: fetch activity details service

- src/app/enter-data/enter-data.component.ts
- src/app/services/sub-area.service.ts
NOBUG
Fixing go button on enter-data.
> NOBUG: Fixing go button on enter-data

- src/app/enter-data/accordion-manager/accordion-manager.component.html
- src/app/enter-data/accordion-manager/accordion-manager.component.ts
BRS-555
https://bcparksdigital.atlassian.net/browse/BRS-555
Accordion list wasnt resetting properly when changing subarea.
> NOBUG: reset accordions when switching subarea

- src/app/app.component.scss
> NO BUG: toggle button is now fixed in place

- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.html
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.scss
- src/app/forms/frontcountry-cabins/sections/frontcountry-cabins-section/frontcountry-cabins-section.component.html
- src/app/forms/frontcountry-cabins/sections/frontcountry-cabins-section/frontcountry-cabins-section.module.ts
- src/app/shared/components/forms/text-input/text-input.component.html
- src/assets/styles/base/base.scss
- src/assets/themes/_variables.scss
BRS-534
https://bcparksdigital.atlassian.net/browse/BRS-534
UI only for frontcountry cabins
> BRS-534: UI for frontcountry cabins

- src/app/forms/day-use/day-use.component.html
- src/app/forms/day-use/sections/other-day-use/other-day-use.component.html
- src/app/forms/day-use/sections/other-day-use/other-day-use.module.ts
- src/app/forms/day-use/sections/people-and-vehicles/people-and-vehicles.component.html
- src/app/forms/day-use/sections/people-and-vehicles/people-and-vehicles.module.ts
- src/app/forms/day-use/sections/picnic-shelters/picnic-shelters.component.html
- src/app/forms/day-use/sections/picnic-shelters/picnic-shelters.module.ts
- src/assets/styles/base/base.scss
BRS-536
https://bcparksdigital.atlassian.net/browse/BRS-536
UI for Day use form added. Another library will need to be imported to get the correct icons for vehicles and buses.
> BRS-536: Day use form UI, small fix in base.scss

- package.json
- src/app/enter-data/accordion-manager/accordion-manager.component.ts
- src/app/enter-data/accordion-manager/backcountry-cabins-accordion/backcountry-cabins-accordion.component.ts
- src/app/enter-data/accordion-manager/backcountry-camping-accordion/backcountry-camping-accordion.component.ts
- src/app/enter-data/accordion-manager/boating-accordion/boating-accordion.component.ts
- src/app/enter-data/accordion-manager/day-use-accordion/day-use-accordion.component.ts
- src/app/enter-data/accordion-manager/frontcountry-cabins-accordion/frontcountry-cabins-accordion.component.ts
- src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.ts
- src/app/enter-data/accordion-manager/group-camping-accordion/group-camping-accordion.component.ts
- src/app/enter-data/enter-data.component.ts
- src/app/enter-data/enter-data.module.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/services/sub-area.service.ts
- src/app/shared/utils/constants.ts
- yarn.lock
NOBUG
Wiring up services for accordion.
> NOBUG: Wiring up services for accordion

- angular.json
> NOBUG: upping budget

- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
- src/app/forms/frontcountry-camping/sections/additional-vehicles/additional-vehicles.component.html
- src/app/forms/frontcountry-camping/sections/additional-vehicles/additional-vehicles.module.ts
- src/app/forms/frontcountry-camping/sections/camping-party-nights/camping-party-nights.component.html
- src/app/forms/frontcountry-camping/sections/camping-party-nights/camping-party-nights.module.ts
- src/app/forms/frontcountry-camping/sections/other-frontcountry-camping-revenue/other-frontcountry-camping-revenue.component.html
- src/app/forms/frontcountry-camping/sections/other-frontcountry-camping-revenue/other-frontcountry-camping-revenue.module.ts
BRS-495
https://bcparksdigital.atlassian.net/browse/BRS-495
> BRS-495: Frontcountry camping form UI

- src/app/forms/group-camping/group-camping.component.html
- src/app/forms/group-camping/sections/standard-rate-groups/standard-rate-groups.component.html
- src/app/forms/group-camping/sections/standard-rate-groups/standard-rate-groups.module.ts
- src/app/forms/group-camping/sections/youth-rate-groups/youth-rate-groups.component.html
- src/app/forms/group-camping/sections/youth-rate-groups/youth-rate-groups.module.ts
BRS-535
https://bcparksdigital.atlassian.net/browse/BRS-535
> BRS-535: group camping form created

- src/app/forms/backcountry-camping/backcountry-camping.component.html
- src/app/forms/backcountry-camping/sections/backcountry-camping-section/backcountry-camping-section.component.html
- src/app/forms/backcountry-camping/sections/backcountry-camping-section/backcountry-camping-section.module.ts
BRS-537
https://bcparksdigital.atlassian.net/browse/BRS-537
> BRS-537: backcountry camping from created

- src/app/forms/backcountry-cabins/backcountry-cabins.component.html
- src/app/forms/backcountry-cabins/sections/backcountry-cabins-section/backcountry-cabins-section.component.html
- src/app/forms/backcountry-cabins/sections/backcountry-cabins-section/backcountry-cabins-section.module.ts
BRS-538
https://bcparksdigital.atlassian.net/browse/BRS-538
> BRS-538: backcountry cabins form created

- src/app/forms/boating/boating.component.html
- src/app/forms/boating/sections/boating-section/boating-section.component.html
- src/app/forms/boating/sections/boating-section/boating-section.module.ts
BRS-539
https://bcparksdigital.atlassian.net/browse/BRS-539
> BRS-539: boating form created

- src/app/app-routing.module.ts
- src/app/enter-data/accordion-manager/backcountry-cabins-accordion/backcountry-cabins-accordion.component.html
- src/app/enter-data/accordion-manager/backcountry-camping-accordion/backcountry-camping-accordion.component.html
- src/app/enter-data/accordion-manager/boating-accordion/boating-accordion.component.html
- src/app/enter-data/accordion-manager/day-use-accordion/day-use-accordion.component.html
- src/app/enter-data/accordion-manager/frontcountry-cabins-accordion/frontcountry-cabins-accordion.component.html
- src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.html
- src/app/enter-data/accordion-manager/group-camping-accordion/group-camping-accordion.component.html
- src/app/enter-data/enter-data.component.html
- src/app/enter-data/enter-data.component.spec.ts
- src/app/enter-data/enter-data.component.ts
- src/app/enter-data/enter-data.module.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/shared/components/accordion/accordion.component.spec.ts
- src/app/shared/components/accordion/accordion.component.ts
NOBUG
Implemented rough routing.
> NOBUG: Implemented rough routing

- src/app/forms/backcountry-cabins/backcountry-cabins.component.html
- src/app/forms/backcountry-cabins/backcountry-cabins.component.spec.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.module.ts
- src/app/forms/backcountry-cabins/sections/backcountry-cabins-section/backcountry-cabins-section.component.html
- src/app/forms/backcountry-cabins/sections/backcountry-cabins-section/backcountry-cabins-section.component.spec.ts
- src/app/forms/backcountry-cabins/sections/backcountry-cabins-section/backcountry-cabins-section.component.ts
- src/app/forms/backcountry-cabins/sections/backcountry-cabins-section/backcountry-cabins-section.module.ts
- src/app/forms/boating/boating.component.html
- src/app/forms/boating/boating.component.ts
- src/app/forms/boating/sections/boating-section/boating-section.component.html
- src/app/forms/boating/sections/boating-section/boating-section.component.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
- src/app/shared/components/forms/text-area/text-area.component.html
- src/app/shared/components/forms/text-area/text-area.component.ts
- src/app/shared/components/forms/text-area/text-area.module.ts
none
https://bcparksdigital.atlassian.net/browse/BRS-
This change stubs out Boating and Backcountry Cabins forms by extending `BaseFormComponent`. Submission logic was also updated to reflect the following:
```
{
form: FormGroup; // the whole form
isValid?: boolean; // the validity of the form
error: any; // errors or error codes
fields?: any; // raw key:value pairs of the form
payload?: any; // object for API submission
invalidFields?: any; // collection of invalid form fields
}
```
> Extending base forms for boating and backcountry cabins

- src/app/app-routing.module.ts
- src/app/enter-data/enter-data.component.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.html
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/resolvers/sub-area.resolver.ts
- src/app/shared/components/select/select.component.html
- src/app/shared/components/select/select.component.ts
- src/app/shared/components/typeahead/typeahead.component.ts
- src/app/shared/utils/utils.ts
NOBUG
Created preload logic for enter-data page.
> NOBUG: created preload logic for enter-data page

- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/services/api.service.ts
- src/app/services/form.service.spec.ts
- src/app/services/form.service.ts
- src/app/shared/components/accordion/accordion.component.ts
- src/app/shared/utils/constants.ts
NOBUG
Creating for service for posting activity.
> NOBUG: Creating for service for posting activity

- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.html
- src/app/forms/group-camping/group-camping.component.spec.ts
- src/app/forms/group-camping/group-camping.component.ts
- src/app/forms/group-camping/group-camping.module.ts
- src/app/forms/group-camping/sections/standard-rate-groups/standard-rate-groups.component.html
- src/app/forms/group-camping/sections/standard-rate-groups/standard-rate-groups.component.spec.ts
- src/app/forms/group-camping/sections/standard-rate-groups/standard-rate-groups.component.ts
- src/app/forms/group-camping/sections/standard-rate-groups/standard-rate-groups.module.ts
- src/app/forms/group-camping/sections/youth-rate-groups/youth-rate-groups.component.html
- src/app/forms/group-camping/sections/youth-rate-groups/youth-rate-groups.component.spec.ts
- src/app/forms/group-camping/sections/youth-rate-groups/youth-rate-groups.component.ts
- src/app/forms/group-camping/sections/youth-rate-groups/youth-rate-groups.module.ts
BRS-123
https://bcparksdigital.atlassian.net/browse/BRS-123
> Extending group camping form

- src/app/enter-data/enter-data.component.html
- src/app/enter-data/enter-data.component.scss
- src/app/enter-data/enter-data.component.ts
- src/app/enter-data/enter-data.module.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.html
- src/app/forms/backcountry-cabins/backcountry-cabins.component.spec.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.html
- src/app/forms/backcountry-camping/backcountry-camping.component.spec.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.html
- src/app/forms/boating/boating.component.spec.ts
- src/app/forms/boating/boating.component.ts
- src/app/forms/day-use/day-use.component.html
- src/app/forms/day-use/day-use.component.spec.ts
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.html
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.spec.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
- src/app/forms/frontcountry-camping/frontcountry-camping.component.spec.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.html
- src/app/forms/group-camping/group-camping.component.spec.ts
- src/app/forms/group-camping/group-camping.component.ts
- src/app/services/api.service.ts
- src/app/services/form.service.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
- src/app/shared/utils/utils.ts
NOBUG
Setting up post for forms.
> NOBUG: Setting up post for forms

- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.ts
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.ts
- src/app/shared/components/forms/base-form/base-form.component.spec.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
- src/app/shared/components/forms/base-form/base-form.module.ts
https://bcparksdigital.atlassian.net/browse/
Moving common logic from individual forms to the BaseFormComponent to eliminate code duplication.
> NOBUG: Moving common form logic to baseformcomponent

- src/app/enter-data/sub-area-search/sub-area-search.component.ts
NOBUG
Fixing subarea filter bug.
> NOBUG: Fixing subarea filter bug

- src/app/shared/components/sidebar/sidebar.component.html
- src/app/shared/components/sidebar/sidebar.component.ts
NOBUG
Fixing sidebar highlight issue when params exist.
> NOBUG: fixing sidebar highlight issue when params exist

- src/app/enter-data/enter-data.component.html
- src/app/resolvers/sub-area.resolver.ts
- src/app/services/sub-area.service.ts
- src/app/shared/components/breadcrumb/breadcrumb.component.html
- src/app/shared/components/breadcrumb/breadcrumb.component.scss
- src/app/shared/components/breadcrumb/breadcrumb.component.ts
- src/app/shared/components/sidebar/sidebar.component.html
- src/app/shared/components/sidebar/sidebar.component.scss
- src/app/shared/components/sidebar/sidebar.component.ts
- src/app/shared/utils/utils.ts
NOBUG
Fixing persisting accordion issue when clicking sidebar or breadcrumb
> NOBUG: fixing persisting accordion issue when clicking sidebar or breadcrumb

- src/app/app-routing.module.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.html
- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.html
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.html
- src/app/forms/boating/boating.component.ts
- src/app/forms/day-use/day-use.component.html
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.html
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.html
- src/app/forms/group-camping/group-camping.component.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
- src/app/shared/components/forms/base-form/base-form.module.ts
NOBUG
https://bcparksdigital.atlassian.net/browse/
- Forms will now prepopulate the fields with the readonly data from the accordion (no new API call is done upon clicking EDIT). 
- Minor routing bug to frontcountry camping fixed.
- More common form logic moved to BaseFormComponent
> NOBUG: form prepopulation

- src/app/shared/components/accordion/accordion.component.html
NOBUG
Fixing accordion arrow initialize up bug.
> NOBUG: Fixing accordion arrow initialize up bug

- src/app/enter-data/accordion-manager/backcountry-cabins-accordion/backcountry-cabins-accordion.component.html
- src/app/enter-data/accordion-manager/backcountry-camping-accordion/backcountry-camping-accordion.component.html
- src/app/enter-data/accordion-manager/boating-accordion/boating-accordion.component.html
- src/app/enter-data/accordion-manager/day-use-accordion/day-use-accordion.component.html
- src/app/enter-data/accordion-manager/frontcountry-cabins-accordion/frontcountry-cabins-accordion.component.html
- src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.html
- src/app/enter-data/accordion-manager/group-camping-accordion/group-camping-accordion.component.html
- src/app/services/sub-area.service.ts
NOBUG
Populating last updated on accordion
> NOBUG: Populating last updated on accordion

- src/app/shared/components/forms/text-input/text-input.component.html
NOBUG
number field error fix
https://github.com/angular/angular/issues/13243
> NOBUG: number field error fix

- src/app/app.component.html
- src/app/app.module.ts
- src/app/enter-data/accordion-manager/boating-accordion/boating-accordion.component.ts
- src/app/services/park.service.spec.ts
- src/app/services/park.service.ts
- src/app/services/sub-area.service.spec.ts
- src/app/services/sub-area.service.ts
- src/app/shared/components/infinite-loading-bar/infinite-loading-bar.component.html
- src/app/shared/components/infinite-loading-bar/infinite-loading-bar.component.scss
- src/app/shared/components/infinite-loading-bar/infinite-loading-bar.component.spec.ts
- src/app/shared/components/infinite-loading-bar/infinite-loading-bar.component.ts
- src/app/shared/components/infinite-loading-bar/infinite-loading-bar.module.ts
- src/app/shared/components/infinite-loading-bar/infinite-loading-bar.service.spec.ts
- src/app/shared/components/infinite-loading-bar/infinite-loading-bar.service.ts
NOBUG
Added an infinite loading bar.
> NOBUG: Added an infinite loading bar

- src/app/enter-data/sub-area-search/sub-area-search.component.html
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
NOBUG
Disabling go button if data is loading.
> NOBUG: disabling go button if data is loading

- src/app/app-routing.module.ts
- src/app/shared/components/breadcrumb/breadcrumb.component.html
- src/app/shared/components/breadcrumb/breadcrumb.component.scss
NOBUG
breadcrumbs for forms added and styled
> NOBUG: breadcrumbs for forms added and styled

- src/app/enter-data/accordion-manager/backcountry-cabins-accordion/backcountry-cabins-accordion.component.ts
- src/app/enter-data/accordion-manager/backcountry-camping-accordion/backcountry-camping-accordion.component.ts
- src/app/enter-data/accordion-manager/boating-accordion/boating-accordion.component.ts
- src/app/enter-data/accordion-manager/day-use-accordion/day-use-accordion.component.ts
- src/app/enter-data/accordion-manager/frontcountry-cabins-accordion/frontcountry-cabins-accordion.component.ts
- src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.ts
- src/app/enter-data/accordion-manager/group-camping-accordion/group-camping-accordion.component.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.ts
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.ts
- src/app/services/formula.service.ts
- src/app/shared/components/accordion/summary-section/summary-section.component.html
- src/app/shared/components/accordion/summary-section/summary-section.component.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
- src/app/shared/components/forms/calculation-display/calculation-display.component.html
- src/app/shared/components/forms/calculation-display/calculation-display.component.ts
BRS-573
https://bcparksdigital.atlassian.net/browse/BRS-573
This change improves `FormulaService`, which should handle all calculations in the application.  All formulas for read-only views have been added to the service.
> BRS-573: FormulaService

- package.json
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/services/form.service.spec.ts
- src/app/services/form.service.ts
- src/app/shared/utils/constants.ts
- src/styles.scss
- yarn.lock
NOBUG
Implemented toast success and error for post activity.
> NOBUG: Implemented toast success and error for post activity

- src/app/services/formula.service.spec.ts
- src/app/services/formula.service.ts
BRS-573
https://bcparksdigital.atlassian.net/browse/BRS-573
Adding UTs for `FormulaService`
> BRS-573: FormulaService UTs

- src/app/app-routing.module.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.ts
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.ts
- src/app/resolvers/form.resolver.spec.ts
- src/app/resolvers/form.resolver.ts
- src/app/services/data.service.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
NOBUG
Enabling copy pasting urls of forms.
> NOBUG: Enabling copy pasting urls of forms

- src/app/shared/components/forms/base-form/base-form.component.ts
NOBUG
Adding the ability to enable/disable all fields in a form simultaneously.
> NOBUG: enable/disable forms

- src/app/forms/backcountry-cabins/backcountry-cabins.component.html
- src/app/forms/backcountry-cabins/backcountry-cabins.module.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.html
- src/app/forms/backcountry-camping/backcountry-camping.module.ts
- src/app/forms/boating/boating.component.html
- src/app/forms/boating/boating.module.ts
- src/app/forms/cancel-button/cancel-button.component.html
- src/app/forms/cancel-button/cancel-button.component.scss
- src/app/forms/cancel-button/cancel-button.component.spec.ts
- src/app/forms/cancel-button/cancel-button.component.ts
- src/app/forms/cancel-button/cancel-button.module.ts
- src/app/forms/day-use/day-use.component.html
- src/app/forms/day-use/day-use.module.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.html
- src/app/forms/frontcountry-cabins/frontcountry-cabins.module.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
- src/app/forms/frontcountry-camping/frontcountry-camping.module.ts
- src/app/forms/group-camping/group-camping.component.html
- src/app/forms/group-camping/group-camping.module.ts
- src/assets/styles/base/base.scss
> NOBUG: Adding cancel button

- src/app/app.module.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.html
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.html
- src/app/forms/boating/boating.component.ts
- src/app/forms/cancel-button/cancel-button.module.ts
- src/app/forms/day-use/day-use.component.html
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.html
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.html
- src/app/forms/group-camping/group-camping.component.ts
- src/app/services/loading.service.spec.ts
- src/app/services/loading.service.ts
- src/app/services/park.service.spec.ts
- src/app/services/park.service.ts
- src/app/services/sub-area.service.spec.ts
- src/app/services/sub-area.service.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
- src/app/shared/components/infinite-loading-bar/infinite-loading-bar.component.ts
- src/app/shared/components/text-to-loading-spinner/text-to-loading-spinner.component.ts
- src/app/shared/components/text-to-loading-spinner/text-to-loading-spinner.module.ts
- src/assets/styles/base/base.scss
> NOBUG: Added loading service

- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.ts
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.html
- src/app/forms/group-camping/group-camping.component.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
NOBUG
Moving loadingService code to BaseFormComponent to avoid code duplication.
Removing superfluous submit button on GroupCamping form.
> NOBUG: moving loadingService to BaseFormComponent, removing button

- src/app/enter-data/accordion-manager/accordion-manager.component.ts
Collapse all accordions when new search performed.
> 54: All accordions should collapse when a new search is performed

- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.ts
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.ts
- src/app/services/validation.service.spec.ts
- src/app/services/validation.service.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
- src/app/shared/components/forms/text-input/text-input.component.html
- src/assets/styles/base/base.scss
- src/assets/themes/_variables.scss
BRS-572
https://bcparksdigital.atlassian.net/browse/BRS-572
This change adds field VALUE validation to all fields. It ensures that before submission of form values, they are all checked for validity. 
* Counter fields are validated to be whole, positive integers with no other characters, allowing only characters `0-9` (and `null`).
* Money fields are validated to be positive or negative decimal numbers (floats), allowing characters `0-9`,`-`, and `.` (and `null`).
- This change does not totally validate the DISPLAY of fields. For example, a user can enter `e` into the counter field and `e` will display in the field, but the field VALUE will evaluate to `null` and therefore will pass as valid. 
- This change will prevent the submit button from submitting values to the API if there are any …
> BRS-572 field validation pt. 1

- src/app/enter-data/sub-area-search/sub-area-search.component.ts
NOBUG
Fixing preload filter bug.
> NOBUG: Fixing preload filter bug

- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.html
BRS-586
https://bcparksdigital.atlassian.net/browse/BRS-586
Fixing group-camping calculations.
> BRS-586 fixing group camping calculations

- src/app/forms/backcountry-cabins/backcountry-cabins.component.html
- src/app/forms/backcountry-camping/backcountry-camping.component.html
- src/app/forms/boating/boating.component.html
- src/app/forms/day-use/day-use.component.html
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.html
- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
- src/app/forms/group-camping/group-camping.component.html
NOBUG
Changing submit text to save.
> NOBUG: changing submit text to save

- src/app/forms/cancel-button/cancel-button.component.html
NOBUG
Changing colour of cancel button.
> NOBUG: Changing colour of cancel button

- src/app/shared/components/breadcrumb/breadcrumb.component.html
- src/app/shared/components/breadcrumb/breadcrumb.component.ts
NOBUG
Last item in breadcrumbs is no longer clickable.
> NOBUG: Last item in breadcrumbs is no longer clickable

- src/app/forms/day-use/sections/picnic-shelters/picnic-shelters.component.html
- src/app/shared/components/breadcrumb/breadcrumb.component.ts
NOBUG
Breadcrumb update. Picnic form label update.
> NOBUG: Breadcrumb update. Picnic form label update

- src/app/forms/backcountry-cabins/backcountry-cabins.component.html
- src/app/forms/backcountry-camping/backcountry-camping.component.html
- src/app/forms/boating/boating.component.html
- src/app/forms/cancel-button/cancel-button.component.html
- src/app/forms/cancel-button/cancel-button.component.ts
- src/app/forms/day-use/day-use.component.html
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.html
- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
- src/app/forms/group-camping/group-camping.component.html
- src/app/shared/components/forms/base-form/base-form.component.ts
BRS-496
Fixing button disabled loading state.
> BRS-496: Fixing button disabled loading state

- src/app/shared/components/breadcrumb/breadcrumb.component.html
- src/app/shared/components/breadcrumb/breadcrumb.component.ts
NOBUG
Fixing breadcrumb errors.
> NOBUG: Fixing breadcrumb errors

- src/app/forms/backcountry-cabins/backcountry-cabins.component.html
- src/app/forms/backcountry-cabins/backcountry-cabins.component.spec.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.module.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.html
- src/app/forms/backcountry-camping/backcountry-camping.component.spec.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.module.ts
- src/app/forms/boating/boating.component.html
- src/app/forms/boating/boating.component.spec.ts
- src/app/forms/boating/boating.module.ts
- src/app/forms/day-use/day-use.component.html
- src/app/forms/day-use/day-use.component.spec.ts
- src/app/forms/day-use/day-use.module.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.html
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.spec.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.module.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
- src/app/forms/frontcountry-camping/frontcountry-camping.component.spec.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.module.ts
- src/app/forms/group-camping/group-camping.component.html
- src/app/forms/group-camping/group-camping.component.spec.ts
- src/app/forms/group-camping/group-camping.module.ts
- src/app/forms/park-header/park-header.component.html
- src/app/forms/park-header/park-header.component.scss
- src/app/forms/park-header/park-header.component.spec.ts
- src/app/forms/park-header/park-header.component.ts
- src/app/forms/park-header/park-header.module.ts
NOBUG: park-header component clean up, import added to test files
NOBUG
Added park name, subarea, and date to each form for clarity.
> NOBUG: form park header component created

- src/app/enter-data/enter-data.component.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.ts
- src/app/forms/cancel-button/cancel-button.component.ts
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.ts
- src/app/forms/park-header/park-header.component.ts
- src/app/resolvers/sub-area.resolver.ts
- src/app/services/form.service.ts
- src/app/shared/components/accordion/accordion.component.ts
- src/app/shared/components/breadcrumb/breadcrumb.component.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
- src/app/shared/utils/constants.ts
74
https://github.com/bcgov/bcparks-ar-admin/issues/74
Retain search params when clicking on breadcrumbs.
> 74: retain search params when clicking on breadcrumbs

- src/app/forms/cancel-button/cancel-button.component.ts
- src/app/forms/park-header/park-header.component.ts
#112 
Correcting some missed subscriptions.
> NOBUG - missed subscribe components from issue #112

- src/app/enter-data/accordion-manager/accordion-manager.component.ts
- src/app/enter-data/accordion-manager/backcountry-cabins-accordion/backcountry-cabins-accordion.component.ts
- src/app/enter-data/accordion-manager/backcountry-camping-accordion/backcountry-camping-accordion.component.ts
- src/app/enter-data/accordion-manager/boating-accordion/boating-accordion.component.ts
- src/app/enter-data/accordion-manager/day-use-accordion/day-use-accordion.component.ts
- src/app/enter-data/accordion-manager/frontcountry-cabins-accordion/frontcountry-cabins-accordion.component.ts
- src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.ts
- src/app/enter-data/accordion-manager/group-camping-accordion/group-camping-accordion.component.ts
- src/app/enter-data/enter-data.component.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.ts
- src/app/forms/cancel-button/cancel-button.component.ts
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.ts
- src/app/forms/park-header/park-header.component.ts
- src/app/header/header.component.ts
- src/app/shared/components/accordion/accordion.component.ts
- src/app/shared/components/breadcrumb/breadcrumb.component.ts
- src/app/shared/components/date-picker/date-picker.component.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
- src/app/shared/components/infinite-loading-bar/infinite-loading-bar.component.ts
- src/app/shared/components/sidebar/sidebar.component.ts
- src/app/shared/components/text-to-loading-spinner/text-to-loading-spinner.component.ts
NOBUG
Removing use of takeWhile.
> NOBUG: Removing use of takeWhile

- src/app/shared/components/accordion/accordion.component.html
- src/app/shared/components/accordion/accordion.component.spec.ts
- src/app/shared/components/accordion/accordion.component.ts
- src/app/shared/components/accordion/summary-section/summary-section.component.html
- src/app/shared/components/centered-text-block/centered-text-block.component.html
- src/app/shared/components/centered-text-block/centered-text-block.component.scss
BRS-556
https://bcparksdigital.atlassian.net/browse/BRS-556
updated UI for accordion components to match ticket BRS-556. Clean-up of unused imports in accordion components.
> BRS-556: updated UI for accordion components to match ticket BRS-556

- src/app/enter-data/sub-area-search/sub-area-search.component.html
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
BRS-591
https://bcparksdigital.atlassian.net/browse/BRS-591
Disabling date select for dates in the future.
> BRS-591: disabling future months

- src/app/services/keycloak.service.ts
BRS-579
https://bcparksdigital.atlassian.net/browse/BRS-579
Fix for isAuthenticated.
> BRS-579: Fix for isAuthenticated.

- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/forms/cancel-button/cancel-button.component.ts
- src/app/resolvers/form.resolver.ts
- src/app/resolvers/sub-area.resolver.ts
- src/app/services/form.service.ts
- src/app/services/sub-area.service.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
BRS-615
https://bcparksdigital.atlassian.net/browse/BRS-615
Following https://github.com/bcgov/bcparks-ar-api/pull/35, there are several changes in the front end necessary to work with the new changes to subarea UID. The above PR must be completed first before testing/merging this one.
> BRS-615 creating subArea UIDs

- terraform/prod/terragrunt.hcl
- terraform/src/cloudfront.tf
BRS-596
https://bcparksdigital.atlassian.net/browse/BRS-596
Vanity Url for A&R.
> BRS-596: Vanity Url for A&R

- src/app/app-routing.module.ts
- src/app/export-reports/export-reports.component.html
- src/app/export-reports/export-reports.component.spec.ts
- src/app/export-reports/export-reports.component.ts
- src/app/export-reports/export-reports.module.ts
- src/app/home/home.component.html
- src/app/resolvers/export.resolver.spec.ts
- src/app/resolvers/export.resolver.ts
- src/app/services/export.service.spec.ts
- src/app/services/export.service.ts
- src/app/shared/utils/constants.ts
BRS-501
https://bcparksdigital.atlassian.net/browse/BRS-501
Setting up export page.
> BRS-501: Setting up export page

- src/app/enter-data/accordion-manager/day-use-accordion/day-use-accordion.component.ts
- src/app/forms/day-use/day-use.component.html
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/day-use/sections/other-day-use/other-day-use.component.html
- src/app/forms/day-use/sections/other-day-use/other-day-use.component.ts
- src/app/forms/day-use/sections/people-and-vehicles/people-and-vehicles.component.html
- src/app/forms/day-use/sections/picnic-shelters/picnic-shelters.component.html
- src/app/forms/day-use/sections/picnic-shelters/picnic-shelters.component.ts
- src/app/services/formula.service.ts
skiing field removed, hot spring people added, trail count added to people and vehicles calc
BRS-626: picnic shelter people field added
BRS-626: UI and text updates
BRS-626
https://bcparksdigital.atlassian.net/browse/BRS-626
> BRS-626: Text, UI and Calculation updates to Day Use

- src/app/services/keycloak.service.ts
BRS-598
https://bcparksdigital.atlassian.net/browse/BRS-598
Changing header text to use preferred username.
> BRS-598: Changing header text to use preferred username

- src/app/services/keycloak.service.ts
BRS-598
https://bcparksdigital.atlassian.net/browse/BRS-598
Changing header display name to use name.
> BRS-598: Changing header display name to use name

- src/app/app-routing.module.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.html
- src/app/forms/backcountry-cabins/sections/backcountry-cabins-section/backcountry-cabins-section.component.html
- src/app/forms/day-use/day-use.component.html
- src/app/forms/day-use/sections/people-and-vehicles/people-and-vehicles.component.html
- src/app/forms/frontcountry-cabins/sections/frontcountry-cabins-section/frontcountry-cabins-section.component.html
- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
- src/app/forms/frontcountry-camping/sections/additional-vehicles/additional-vehicles.component.html
- src/app/forms/group-camping/group-camping.component.html
- src/app/forms/group-camping/sections/standard-rate-groups/standard-rate-groups.component.html
- src/app/forms/group-camping/sections/youth-rate-groups/youth-rate-groups.component.html
- src/app/services/formula.service.ts
BRS-612
https://bcparksdigital.atlassian.net/browse/BRS-612
UI Refinements - individual forms
> BRS-612: updates made to UI to match designs

- src/app/forms/day-use/sections/other-day-use/other-day-use.component.html
BRS-626
https://bcparksdigital.atlassian.net/browse/BRS-626
> BRS-626: minor padding change to Day Use form

- src/app/enter-data/accordion-manager/backcountry-cabins-accordion/backcountry-cabins-accordion.component.ts
- src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.ts
- src/app/enter-data/accordion-manager/group-camping-accordion/group-camping-accordion.component.ts
- src/app/forms/backcountry-cabins/sections/backcountry-cabins-section/backcountry-cabins-section.component.html
- src/app/forms/boating/sections/boating-section/boating-section.component.html
- src/app/services/formula.service.ts
BRS-612
https://bcparksdigital.atlassian.net/browse/BRS-612
> BRS-612: text changes to match Figma designs

- src/app/app.module.ts
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/services/form.service.ts
- src/app/services/keycloak.service.ts
- src/env.js
BRS-643
https://bcparksdigital.atlassian.net/browse/BRS-643
This is the front-end piece for PR: https://github.com/bcgov/bcparks-ar-api/pull/56
> BRS-643: Role assignment for Sub-areas in A&R

- src/app/services/formula.service.spec.ts
- src/app/services/formula.service.ts
BRS-692
https://bcparksdigital.atlassian.net/browse/BRS-692
This change updates the basic net revenue calculation.
Old formula: Net = Gross*(1-percentage)
New formula: Net = Gross/(1+percentage)
> BRS-692: updating net revenue formula

- src/app/forms/day-use/sections/people-and-vehicles/people-and-vehicles.component.html
BRS-717
https://bcparksdigital.atlassian.net/browse/BRS-717
Text change on Day Use form.
> BRS-717: Text change on Day Use form

- src/app/home/home.component.html
BRS-707
https://bcparksdigital.atlassian.net/browse/BRS-707
Align boxes based on feedback.  Update JIRA ticket to include new reqs.
> BRS-707: Center align boxes.

- src/app/enter-data/enter-data.component.ts
NOBUG
Fixed issue where page was rendering before formParams was populated causing console errors.
> NOBUG: fixed issue where page was rendering before variable set

- src/app/footer/footer.component.html
- src/app/footer/footer.component.scss
BRS-604
https://bcparksdigital.atlassian.net/jira/software/projects/BRS/boards/1?selectedIssue=BRS-604
Updated the footer with the new quick links according to screenshot. But with a new PR in a new branch with signed commits this time. No actual change compared to the [previous PR](https://github.com/bcgov/bcparks-ar-admin/pull/149).
> BRS-604: Adjust A&R Footer, with signed commits

- src/app/enter-data/accordion-manager/backcountry-cabins-accordion/backcountry-cabins-accordion.component.html
- src/app/enter-data/accordion-manager/backcountry-camping-accordion/backcountry-camping-accordion.component.html
- src/app/enter-data/accordion-manager/boating-accordion/boating-accordion.component.html
- src/app/enter-data/accordion-manager/day-use-accordion/day-use-accordion.component.html
- src/app/enter-data/accordion-manager/frontcountry-cabins-accordion/frontcountry-cabins-accordion.component.html
- src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.html
- src/app/enter-data/accordion-manager/group-camping-accordion/group-camping-accordion.component.html
- src/app/shared/components/accordion/accordion.component.html
- src/app/shared/components/accordion/accordion.component.scss
- src/assets/styles/base/base.scss
BRS-629
https://bcparksdigital.atlassian.net/browse/BRS-629
Implemented the layout shown in https://bcparksdigital.atlassian.net/browse/BUX-133 for desktop, and the mobile layout shown in BRS-629.
> BRS-629: Move edit button within accordions

- src/app/enter-data/enter-data.component.ts
- src/app/footer/footer.component.html
- src/app/footer/footer.component.scss
BRS-604
https://bcparksdigital.atlassian.net/browse/BRS-604
Due to a miscommunication, only some changes were partially merged by the last PR. https://github.com/bcgov/bcparks-ar-admin/pull/155
This PR is to actually fully merge all the CSS changes.
> BRS-604: New PR due to certain changes not added into last PR

- src/app/forms/frontcountry-cabins/sections/frontcountry-cabins-section/frontcountry-cabins-section.component.html
BRS-688
https://bcparksdigital.atlassian.net/browse/BRS-688
Added tools tips to frontcountry cabins form.
> BRS-688: Added tooltips to frontcountry cabins

- src/app/enter-data/sub-area-search/sub-area-search.component.scss
- src/app/shared/components/typeahead/typeahead.component.ts
BRS-770
https://bcparksdigital.atlassian.net/browse/BRS-770
This is the admin side of the park dropdown changes. See https://bcparksdigital.atlassian.net/browse/BRS-809 for more info about the api changes.
> BRS-770: dropdown with full parks list (admin changes only)

- src/app/shared/components/accordion/accordion.component.ts
BRS-627
https://bcparksdigital.atlassian.net/browse/BRS-627
Changes to edit button scroll position behaviour
> BRS-627: edit button now scrolls user to top of page

- src/app/enter-data/accordion-manager/group-camping-accordion/group-camping-accordion.component.ts
- src/app/services/formula.service.ts
BRS-605
https://bcparksdigital.atlassian.net/browse/BRS-605
UI Refinements for read only views
> BRS-605: UI Refinements for read only views

- src/app/lock-records/lock-records.component.html
- src/app/lock-records/lock-records.component.ts
- src/app/shared/utils/utils.ts
BRS-817
https://bcparksdigital.atlassian.net/browse/BRS-817
Disabling locking of current and future fiscal years as per ticket designs.
> BRS-817-2 disabling future dates

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- .github/workflows/pr-linting.yaml
- .github/workflows/pr-tests.yaml
Reverts bcgov/bcparks-ar-admin#164 (not required)
> Revert "NOBUG updating Actions to use Node16"

- src/app/lock-records/fiscal-year-lock-table/fiscal-year-lock-table.component.ts
- src/app/lock-records/lock-records.component.html
- src/app/lock-records/lock-records.component.ts
- src/app/services/fiscal-year-lock.service.ts
- src/app/services/form.service.ts
- src/app/shared/components/accordion/accordion.component.html
- src/app/shared/components/accordion/accordion.component.ts
- src/app/shared/components/table/table-row/table-row.component.html
- src/app/shared/components/table/table.component.ts
BRS-831
https://bcparksdigital.atlassian.net/browse/BRS-831
Updates to UI as per BRS-831.
Refactored edit/lock button display to fix NG0100 error.
> BRS-831 fiscal year lock UI updates

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- .github/workflows/pr-linting.yaml
- .github/workflows/pr-tests.yaml
- src/app/services/breadcrumb.service.ts
- src/app/shared/components/sidebar/sidebar.component.ts
NOBUG
Updating flows to use Node 16. Minor sidebar and breadcrumb fixes.
> NOBUG: Updating flows to use Node 16. Minor sidebar and breadcrumb fixes

- angular.json
- karma.conf.js
- package.json
This enabled code coverage on the cli.
> NOBUG: Enable code coverage on cli.

- package.json
- src/app/services/auto-fetch.service.ts
- src/app/services/config.service.ts
- src/app/services/export.service.ts
- src/app/services/fiscal-year-lock.service.ts
- src/app/services/keycloak.service.ts
- src/app/services/logger.service.spec.ts
- src/app/services/logger.service.ts
- src/app/services/park.service.ts
- src/app/services/sub-area.service.ts
- src/env.js
- src/env.js.template
- yarn.lock
BRS-948
https://bcparksdigital.atlassian.net/browse/BRS-948
This improves the front-end logging service for A&R.
> BRS-948 Improve logging in front-end.

- src/app/services/keycloak.service.spec.ts
- src/app/services/keycloak.service.ts
- src/env.js
- src/env.js.template
BRS-975
https://bcparksdigital.atlassian.net/browse/BRS-975
Points default bulids to new loginproxy OIDC by default.
> BRS-975: Point to new loginproxy by default.

- .github/workflows/deploy_test.yml
BRS-961
https://bcparksdigital.atlassian.net/browse/BRS-961
Updating test workflow.
> BRS-961: Updating test workflow

- src/app/home/home.component.spec.ts
BRS-966
Increasing code coverage for home component to 💯
> BRS-966: Increase code coverage of home component.

- src/app/header/header.component.spec.ts
BRS-966
This improves code coverage for the header component.
> BRS-966: Improvements over header component code coverage.

- src/app/shared/utils/utils.spec.ts
BRS-966
This adds some code coverage tests to AR-admin.
> BRS-966: Adding CC.

- src/app/shared/components/breadcrumb/breadcrumb.component.spec.ts
BRS-966
This adds code coverage to 82% for breadcrumb component.
> BRS-966: Adding CC 82% breadcrumb component.

- src/app/services/sub-area.service.spec.ts
BRS-966
Updating more code coverate UT's for admin.
> BRS-966: Updating more CC for admin.

- src/app/login/login.component.spec.ts
BRS-966
Adding unit test code coverage @💯 for login component.
> BRS-966-6: Unit tests for login component.

- src/app/lock-records/fiscal-year-lock-table/fiscal-year-lock-table.component.spec.ts
BRS-966
Adding ut coverage 💯% to fiscal year lock table.
> BRS-966: Adding ut coverage 100% to fiscal year lock table.

- src/app/services/logger.service.spec.ts
BRS-966
Adding up to 80% CC for logger service.
> BRS-966: Adding up to 80% CC for logger.

- src/app/services/park.service.spec.ts
BRS-966
Adding 💯 % CC for park service ut's.
> BRS-966: Adding 100% CC for park service.

- src/app/services/loading.service.spec.ts
BRS-966
Adding CC 💯% to loading service.
> BRS-966: Adding CC 100% to loading service.

- src/app/services/api.service.spec.ts
BRS-966
Adds some code coverage for api service.
> BRS-966: CC for api service.

- src/app/services/config.service.spec.ts
- src/app/services/config.service.ts
- src/app/services/export.service.spec.ts
BRS-966
Adding CC to export and config service.
> BRS-966: Adding CC to export and config service.

- src/app/enter-data/sub-area-search/sub-area-search.component.spec.ts
BRS-966
Adding code coverage 80+% for subAreaSearch component
> BRS-966: Adding code coverage 80+% for subAreaSearch component

- src/app/forms/cancel-button/cancel-button.component.spec.ts
BRS-966
Cancel button component code coverage 💯%
> BRS-966: Cancel button component code coverage 100%

- src/app/shared/utils/jwt-utils.spec.ts
- src/app/shared/utils/jwt-utils.ts
BRS-966
Adding code coverage to jwt utils.
> BRS-966: Adding code coverage to jwt utils.

- src/app/forms/park-header/park-header.component.spec.ts
BRS-966
Adding 💯% code coverage for park-header.
> BRS-966: Adding 100% code coverage for park-header.

- src/app/export-reports/export-reports.component.spec.ts
- src/app/export-reports/export-reports.component.ts
BRS-966
Adding Code Coverage  > 80% for export-reports component.
> BRS-966: Adding Code Coverage  > 80% for export-reports component.

- src/app/shared/components/date-picker/date-picker.component.spec.ts
BRS-966
Adding 💯% code coverage for date-picker component.
> BRS-966: Adding 100% code coverage for date-picker component.

- src/app/resolvers/sub-area.resolver.spec.ts
BRS-966
Adding code 💯% coverage to sub-area resolver.
> BRS-966: Adding code coverage to sub-area resolver.

- src/app/shared/components/sidebar/sidebar.component.spec.ts
BRS-966
Added sidebar component code coverage.
> BRS-966: Added sidebar component code coverage.

- src/app/enter-data/accordion-manager/accordion-manager.component.spec.ts
- src/app/export-reports/export-reports.component.spec.ts
reports spec.
BRS-966
Add code coverage for accordion-manager and tweak export reports spec.
> BRS-966: Add code coverage for accordion-manager and tweak export reports spec.

- package.json
- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- yarn.lock
BRS-1041
https://bcparksdigital.atlassian.net/browse/BRS-1041
This updates the date control UI when a future date has been selected.
> BRS-1041: Update date control UI when they select a future date.

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
BRS-1051
https://bcparksdigital.atlassian.net/browse/BRS-1051
Updating workflows.
> BRS-1051: Updating workflows

- src/app/services/keycloak.service.ts
BRS-989
https://bcparksdigital.atlassian.net/browse/BRS-989
This removes the restriction for only sysadmins seeing the export-reports.  Combine with https://github.com/bcgov/bcparks-ar-api/pull/122
> BRS-989: Enable export A&R report by roles.

- src/app/enter-data/sub-area-search/sub-area-search.component.ts
- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.ts
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.ts
- src/app/services/activity.service.spec.ts
- src/app/services/activity.service.ts
- src/app/services/form.service.ts
- src/app/services/sub-area.service.spec.ts
- src/app/services/sub-area.service.ts
- src/app/shared/components/forms/base-form/base-form.component.ts
BRS-1094
https://bcparksdigital.atlassian.net/browse/BRS-1094
Moving activity related service to ActivityService.
NOTE: This must be deployed at the same time as https://github.com/bcgov/bcparks-ar-api/pull/123
> BRS-1094: Moving activity related code to ActivityService

- package.json
- yarn.lock
BRS-1147
https://bcparksdigital.atlassian.net/browse/BRS-1147
Bumping version of bcparks bootstrap.
> BRS-1147: bumping version of bcparks bootstrap.

- src/app/header/header.component.scss
BRS-660
https://bcparksdigital.atlassian.net/browse/BRS-660
Fixing mobile hamburger item selection.
> BRS-660: Fixing mobile hamburger item selection

- package.json
- yarn.lock
BRS-848
https://bcparksdigital.atlassian.net/browse/BRS-848
Upping version of bootstrap to fix danger colour accessibility issues.
> BRS-848: Upping version of bootstrap to fix danger colour accessibility issues

- src/app/shared/utils/constants.ts
- src/app/shared/utils/variance-utils.spec.ts
- src/app/shared/utils/variance-utils.ts
- tsconfig.json
BRS-1193
https://bcparksdigital.atlassian.net/browse/BRS-1193
Added variance util.
> BRS-1193: Added variance util

- CODEOFCONDUCT.md
- README.md
BRS-123
https://bcparksdigital.atlassian.net/browse/BRS-123
> BRS-1204: Redid CoC, README.md (#238)

- README.md
Final technical updates to readme.md thanks cam! #goatmoves
> BRS-1204 final technical updates w/ cam

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- terraform/terragrunt.hcl
BRS-1152
https://bcparksdigital.atlassian.net/browse/BRS-1152
Update TFC to use TF via s3.
> BRS-1152: Update TFC to use TF via s3

- terraform/terragrunt.hcl
BRS-1152
https://bcparksdigital.atlassian.net/browse/BRS-1152
Fix role assignment.
> BRS-1152: Fix role assignment.

- angular.json
- package.json
- src/app/export-reports/export-reports.component.html
- src/app/export-reports/export-reports.component.spec.ts
- src/app/export-reports/export-reports.component.ts
- src/app/export-reports/export-reports.module.ts
- src/app/resolvers/export.resolver.ts
- src/app/services/export.service.spec.ts
- src/app/services/export.service.ts
- src/app/shared/utils/constants.ts
- src/app/variance-search/variance-list/variance-list.component.ts
- yarn.lock
BRS-1198
https://bcparksdigital.atlassian.net/browse/BRS-1198
This change add the variance export to the exporters. You must provide a fiscal year end to generate a report.
> BRS-1198: variance exporter

- src/app/variance-search/variance-list/variance-list.component.ts
BRS-1249
https://bcparksdigital.atlassian.net/browse/BRS-1249
Fun fact, this is my 6th ticket today
> BRS-1249 fixing view/edit button alignment

- src/app/resolvers/form.resolver.ts
BRS-1266
https://bcparksdigital.atlassian.net/browse/BRS-1266
Record headers were updating conditionally. Now they update no matter what.
> BRS-1266 record headers update from URL

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- .github/workflows/on-pr.yaml
> NOBUG: Updating workflows

- src/app/enter-data/accordion-manager/backcountry-cabins-accordion/backcountry-cabins-accordion.component.ts
Updates title from Family => Gross
> 266: Backcountry Cabin Form needs updated title

- src/app/export-reports/export-reports.component.html
- src/app/export-reports/export-reports.component.ts
- src/app/lock-records/lock-records.component.ts
> 258: UI issues on the Export variance data page.

- src/app/enter-data/accordion-manager/day-use-accordion/day-use-accordion.component.ts
- src/app/forms/day-use/day-use.component.html
- src/app/services/formula.service.ts
AR-263
https://github.com/bcgov/bcparks-ar-admin/issues/263
Updating day use display text.
> AR-263: Updating day use display text

- src/app/forms/day-use/day-use.component.html
BRS-312
[BRS-312](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=54162549)
Updated title on the Day Use enter data page.
> BRS-312: Update Day Use title

- src/app/enter-data/accordion-manager/frontcountry-camping-accordion/frontcountry-camping-accordion.component.ts
- src/app/services/formula.service.ts
Relates to https://github.com/bcgov/bcparks-ar-admin/issues/256
> PDR-256 adding camping nights field

- src/app/forms/backcountry-camping/backcountry-camping.component.html
- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
https://github.com/bcgov/bcparks-ar-admin/issues/316
> adding missing FC camping help text

- src/app/forms/root-form/root-form.component.ts
https://github.com/bcgov/bcparks-ar-admin/issues/322
Hides popup if it will be empty anyways. Full fix with migration incoming after.
> NOBUG dont show historical average popup if it doesnt exist

- src/app/variance-search/variance-filters/variance-filters.component.ts
BRS-260
#260 
Small change to date input so the `X` button to clear/reset date appears for the user.
- Make a small change to `setDate()` so that the form is set as `markAsDirty` on load, which will trigger the `resetButton` to show for the user.
> BRS-260: Update date input to show resetButton, allow user to clear

- src/app/export-reports/export-reports.component.ts
BRS-363
[BRS-363](https://github.com/bcgov/bcparks-ar-admin/issues/363)
- Re-enable the `setMaxDate` method, will check if we're past April to enable the next fiscal year availability on `ngOnInit`
- Linting fixes
> BRS-363: Increase the Fiscal Year availability

- src/app/export-reports/export-reports.component.html
Bugfix for switching between Standard and Variance report tabs
> BRS-363-1: Fix event for tab switch

- src/app/export-reports/export-reports.component.html
- src/app/export-reports/export-reports.component.scss
- src/app/export-reports/export-reports.component.ts
- src/app/export-reports/export-reports.module.ts
- src/app/guards/auth.guard.ts
- src/app/home/home.component.ts
- src/app/services/export.service.ts
- src/app/shared/utils/constants.ts
BRS-351
#351
- Add a tab for Missing Data export
- Add UI for exporting all parks or a single park
- Linting Fixes to applicable files
> BRS-351: Add Missing/Null Values Data Export

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
BRS-359
#359 
- Fix to GitHub Action deploys
> BRS-359-1: Fix to GA deploys

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
BRS-359
#359 
- Fix working_directory on GitHub Actions Deploys
> BRS-359-2: Fix working_directory on GitHub Actions Deploys

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- template.yaml
BRS-359
#359 
- Fix double slash appearing in CloudFront Errors, Default Root, etc.
> BRS-359-3: Remove "/" from BaseHref

- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
BRS-359
#359 
- Fix GitHub Actions for test/prod deploy, should properly create version directories in the S3 bucket on upload
> BRS-359-5: Fix S3 $DIR_NAME Variable in Test/Prod Deploy Actions

- src/app/export-reports/export-reports.component.ts
- src/app/services/export.service.ts
BRS-384
#384 
- Informs the user when no data is returned from a Missing Export search
> BRS-384: Update Missing Export for "No Data"

- src/app/forms/backcountry-cabins/backcountry-cabins.component.ts
- src/app/forms/backcountry-camping/backcountry-camping.component.ts
- src/app/forms/boating/boating.component.ts
- src/app/forms/day-use/day-use.component.ts
- src/app/forms/frontcountry-cabins/frontcountry-cabins.component.ts
- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/forms/group-camping/group-camping.component.ts
- src/app/forms/root-form/root-form.component.ts
Resolves #361 
Increases character limit for variance note field to 200.
Unifies character limit parameter in `root-form` file so the limit is not individually set for each form.
> BRS-361 Increase variance note character limit to 200

- src/app/export-reports/export-reports.component.html
- src/app/export-reports/export-reports.component.scss
- src/app/export-reports/export-reports.component.ts
- src/app/services/export.service.ts
BRS-254
#254 
- Fixed the styling issues so "Export all" is the appropriate size as per the Figma design, and fix the calendar wrapping issue for the months (in dropdown and input box).
- Fixed an issue with the download after "Generate report" is clicked - now passes the `dateRangeStart` and `dateRangeEnd` params (if they exist) in the `getJob:true` event.
> BRS-254-Fix: Styling Issues and the Export Job

- src/app/export-reports/export-reports.component.html
- src/app/export-reports/export-reports.component.scss
- src/app/export-reports/export-reports.component.ts
- While fixing issues with the Missing/Null export, noticed that there was an issue with the Calendar Date Input width from the styling changes made in #411 
- Also fixed the issue with the exporter progress bar showing dozens of decimal places while running
> BRS-377-1: Fix Export Progress Percentage, Fix Date Input Width Issue

- src/app/forms/frontcountry-camping/frontcountry-camping.component.ts
- src/app/services/formula.service.ts
BRS-389
#389 
- Update form so it loads and shows Winter data if it exists on the record
- Update the TOTAL ATTENDANCE formula if winter data is available
> BRS-389-1 - Implement Winter Camping Data Fields (Fix)

- src/app/forms/frontcountry-camping/frontcountry-camping.component.html
BRS-389
#389 
- Fix winter and standard headings on FC form
> BRS-389-2 - Implement Winter Camping Data Fields (Fix)

- src/app/export-reports/export-reports.component.ts
Ticket: [BRS-426](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=96032654&issue=bcgov%7Cbcparks-ar-admin%7C426)
Notes: 
* Confirmed this was limited to front end. 
* Updated the settings for the start and end date displayed when (fiscal) year is selected.
> BRS: 426 - Fiscal Year Correction

- src/app/manage-subareas/review-modal/review-modal.component.html
- src/app/manage-subareas/review-modal/review-modal.component.spec.ts
- src/app/manage-subareas/review-modal/review-modal.component.ts
- src/app/manage-subareas/subarea-form/subarea-form.component.ts
Changes as requested in #427 comments.
Notes:
- request 1 is not in the designs and should be a new ticket.
- request 5 has been completed here but requires a bit of snowflake code since the API expects Capital Casing for activity types
- request 6 is a change request for the forms engine and has been captured in https://github.com/digitalspace/ngds-toolkit/issues/22
- request 7 is not in the designs and should be a new ticket
The rest of the requests are completed in this PR.
> AR-427-4 sendback changes

- src/app/forms/day-use/day-use.component.html
- src/app/forms/root-form/root-form.component.ts
> AR-393-2 fixes
